NoCache middleware
gin-gonic/contrib pull request #197
Opened 2020-09-11 05:09 UTC by alexander-melentyev

NoCache is a simple piece of middleware that sets a number of HTTP headers to prevent a router (or subrouter) from being cached by an upstream proxy and/or client.

2020-09-12 19:20 UTC, appleboy requested changes

2020-09-12 19:20 UTC, appleboy commented on README.md
> ++ [gin-cors](https://github.com/gin-contrib/cors) - Official CORS gin's middleware
duplicate of line?

2020-09-12 19:24 UTC, alexander-melentyev commented on README.md
> ++ [gin-cors](https://github.com/gin-contrib/cors) - Official CORS gin's middleware
Yes, I fix it

2020-09-13 00:51 UTC, appleboy approved these changes

2020-09-13 00:51 UTC, merged